spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE # Proxy 가 가로채는 것을 확인해보자.
        orm:
          jpa:
            JpaTransactionManager: DEBUG # Transaction Rollback 여부 확인방법
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG # Transaction Rollback 여부 확인
      hibernate:
        SQL: DEBUG
        resource:
          transaction: DEBUG # Transaction Rollback 여부 확인
